### ISSUE TITLE
Qué sacar en cada informe

### ISSUE THREAD

**Issue by anacid** [gregorioruiz/hierrosforo#15]
Para los 3 informes, se consideran sólo las facturas o lo pendiente o en albaranes que se facturará después.

**Comment by anacid** [comment]
Para los informes:
1º.- Los tiques que genera en efectivo son los que salen en los listados.
2º.- Los tiques que aparca para que luego los factura su compañero, con esos tiques ella no hace nada.
3º.- Los tiques que aparca y que factura a los dos o tres días, esos si deben de aparecer en el listado, porque los paga ella. En estos tiques aparcados tenemos que tener en cuenta, que deben mantener la fecha de entrada para los precios, pero para los listados la fecha de ese tique es la fecha de pago.

**Comment by gregorioruiz** [comment]
Muchísimas gracias. Está perfectamente explicado.
(Otra cosa es que lo entienda bien y lo sepa hacer .... )
