### ISSUE TITLE
MOdificar menú de albaranes

### ISSUE THREAD

**Issue by gregorioruiz** [gregorioruiz/hierrosforo#21]
![ScreenClip.png](https://zube.io/files/gregorioruiz/5d0603c48c78378a585cdd0801f8bc12.png)

**Comment by gregorioruiz** [comment]
No dejar dar de alta albaranes de forma manual

**Comment by anacid** [comment]
El concepto de albaranes, lo tenemos que ver, porque en realidad no se si para ella será útil.
De momento los filtros de aparcado, facturar, funcionan.

**Comment by gregorioruiz** [comment]
Ya está cambiado todo el concepto de lo que son albaranes y de hecho, ya no existe el menú.
