### ISSUE TITLE
Alta de contacto.

### ISSUE THREAD

**Issue by gregorioruiz** [gregorioruiz/hierrosforo#24]
![ScreenClip.png](https://zube.io/files/gregorioruiz/535a8c558660dbb97838780b54661db4.png)

**Comment by gregorioruiz** [comment]
En el formulario de proveedores, hacer una rejilla que lleve las sumas de compras anuales.

**Comment by gregorioruiz** [comment]
Borrar todo menos los datos principales y la consulta de Notas, albaranes y tickets

**Comment by anacid** [comment]
Ok, al alta de un contacto.
Pero en un contacto, "mas datos", debemos ocultar, la pestañas de:

![ScreenClip.png](https://zube.io/files/gregorioruiz/9c6b25e799a9b2e9b1d230ff1c214afc.png)
