### ISSUE TITLE
Albaranes directos desde la nota

### ISSUE THREAD

**Issue by gregorioruiz** [gregorioruiz/hierrosforo#25]
Casi que no se genere albarán, sino que se queda en nota con estado Albarán.
En ese proceso se imprime esa nota para entregarla a quien factura.

**Comment by gregorioruiz** [comment]
![ScreenClip.png](https://zube.io/files/gregorioruiz/b9e581ca773425b5146cffd208ce0e50.png)

**Comment by gregorioruiz** [comment]
Al aceptar y convertir en albarán se imprime el informe que venía con vERP.

Revisarlo para que sirva para pasarlo a la persona que lo grabará para facturar.

**Comment by anacid** [comment]
Si una nota la damos como "albarán", que esa nota aparezca en el proveedor en la pestaña de albaranes, y que no se pueda modificar, si consultar e imprimir para nada más.

![ScreenClip.png](https://zube.io/files/gregorioruiz/43e17618db75ff3169a58593a05c624a.png)

![ScreenClip.png](https://zube.io/files/gregorioruiz/662e45ec25182e96c604e9ddad7773f1.png)

**Comment by anacid** [comment]
Al hacer una nota y pasarla como albarán, cuando vamos al proveedor, figura en la pestaña de Pedidos (imagino que aqui figurarán todas las notas) y además figura en Albaranes.
