### ISSUE TITLE
Dividir un ticket

### ISSUE THREAD

**Issue by gregorioruiz** [gregorioruiz/hierrosforo#27]
![ScreenClip.png](https://zube.io/files/gregorioruiz/4d1ea2d96dc63e905afc555de5cd743f.png)

**Comment by anacid** [comment]
El proceso lo hacer, creamos una nota, esa nota la dividimos y lo hace bien, pero mis dudas son: a la hora de facturar esos tickets, el primero lo deja como factura de venta sin confirmar, y el segundo, lo doy como ticket directo y aparece como facturado. Creo que este proceso debemos simplificar en lo posible,

![ScreenClip.png](https://zube.io/files/gregorioruiz/4e8c2fdd31cc6b90f8f4ddc1148ba7ab.png)
![ScreenClip.png](https://zube.io/files/gregorioruiz/1648677a57d34aa704898632169a3ad5.png)
![ScreenClip.png](https://zube.io/files/gregorioruiz/00a68c211f261afc31a46069f956adaf.png)
![ScreenClip.png](https://zube.io/files/gregorioruiz/f0ba18f6f7e1d6f57eb819ee89e29732.png)
![ScreenClip.png](https://zube.io/files/gregorioruiz/faf3b7e79a17c544244aabd82d71ca5c.png)
