### ISSUE TITLE
Lista de pedidos de compra - Poner un temporizador para que se recargue sin tener que pulsar buscar

### ISSUE THREAD

**Issue by gregorioruiz** [gregorioruiz/hierrosforo#3]
Desde esta aplicación, se controlará toda la actividad de la entrada de material. Una 

vez se han realizado los pesajes, la información de los mismos, aparecerá en tiempo 

real en la interfaz de monitorización.

**Comment by anacid** [comment]
Donde se va a poner esta aplicación, imagino que en notas? 
De momento no esta, no?

**Comment by gregorioruiz** [comment]
Ya está, y rehace la búsqueda que tengan puesta cada poco tiempo.
