### ISSUE TITLE
agrupar varias notas en un solo recibo.

### ISSUE THREAD

**Issue by gregorioruiz** [gregorioruiz/hierrosforo#5]
Facturar varios albaranes de un mismo cliente

**Comment by anacid** [comment]
He hablado con Vanesa, y me dice que si se puede dar el caso de que tenga varias notas y juntarlas en un solo ticket.

**Comment by anacid** [comment]
Si creo dos notas, las aparco, y luego las factura juntas, me hace la factura correctamente,

![ScreenClip.png](https://zube.io/files/gregorioruiz/483ebfa0bf21f2c3a75883c4c9bc4966.png)

Pero creo que sería más rápido, para ella, que si desde notas, seleccionando las aparcadas, por supuesto del mismo cliente, que directamente saliera el ticket.

![ScreenClip.png](https://zube.io/files/gregorioruiz/9569427854996b8f3bd6ce683ffea0a7.png)

**Comment by gregorioruiz** [comment]
Esto es en ventas. Hacer lo mismo en compras, si no está hecho ya y no lo encuentro.

![ScreenClip.png](https://zube.io/files/gregorioruiz/7cd604b8891bff75a938e5349553c3aa.png)

**Comment by gregorioruiz** [comment]
![ScreenClip.png](https://zube.io/files/gregorioruiz/093d62f0300b70c1dc62ed9ec17b260f.png)
